### ISSUE TITLE
Add flipY to pc.Texture

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1036]
The engine currently enforces a flip in the Y axis for any image set on a texture. This might not always be desired. The [glTF spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#images) requires that this flip be disabled. Therefore, I propose we add a property flipY to pc.Texture, and when the device uploads the texture, we pass it to pixelStorei here:

https://github.com/playcanvas/engine/blob/master/src/graphics/device.js#L1467

Implementation question: should a flipY property just apply for 2D image/canvas/video? Or should it also apply to byte array uploads? Cubemaps?

**Comment by guycalledfrank** [comment]
Editor-wise could a single asset checkbox. If generated compressed textures need to be flipped, we'd do it before compression.
Flipping DXT/PVR/ETC in engine is not as straightforward, they're made of blocks, not pixels, I would avoid it.

**Comment by willeastcott** [comment]
Good point, I hadn't considered the texture compression process. Flipping the image pre-compression makes sense. For now, I've overridden the entire pc.GraphicsDevice#uploadTexture function just to switch true to false. But we can't release the glTF reader until engine support arrives for this.

**Comment by willeastcott** [comment]
FIxed in https://github.com/playcanvas/engine/pull/1051

**Comment by willeastcott** [comment]
This PR is not deployed to production. It can't possibly be affecting your project on playcanvas.com. It's more likely you've changed something in your demo. But if it is due to a change in the engine, you can run your app with an older version of the engine. Just add:

?use_local_engine=https://code.playcanvas.com/playcanvas-0.219.4.js

to the launch URL to use the previously deployed engine. Or update the version number to go back even further.

**Comment by highvrahos** [comment]
Yes, you are right, using previous engine builds doesn't seem to resolve this.

Thanks for the quick reply! I will debug and see what might have changed.
