### ISSUE TITLE
TextureTransformTest.gltf gives an error when trying to display

### ISSUE THREAD

**Issue by cx20** [playcanvas/engine#2060]
### Description

I tried to display [TextureTransformTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformTest) in PlayCanvas.
However, the error was output to the console and the model was not displayed.

Probably an error occurs when there is no sampler in the texture property.
```
  "textures": [
    {
      "source": 0,
      "sampler": 0
    },
    {
      "source": 1,
      "sampler": 0
    },
    {
      "source": 2
    },
          :
  ],

```

### Steps to Reproduce

[PlayCanvas + TextureTransformTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/2d41fd8151d66d982551c5b6c38ae4d68b56e521/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformTest&scale=1&type=glTF)

```javascript
playcanvas-latest.js:45457 
Uncaught TypeError: Cannot read property 'minFilter' of undefined
    at createTexture (playcanvas-latest.js:45457)
    at playcanvas-latest.js:45588
    at Array.map (<anonymous>)
    at createTextures (playcanvas-latest.js:45587)
    at createResources (playcanvas-latest.js:45621)
    at playcanvas-latest.js:45830
    at onLoad (playcanvas-latest.js:45666)
```

![image](https://user-images.githubusercontent.com/1833979/81201974-e71c1b00-9000-11ea-93a0-e032d8bc2b6b.png)

**Comment by slimbuck** [comment]
Indeed... thank you again for pointing this out :)

**Comment by cx20** [comment]
I've tested with the latest version and confirmed that the `undefined` issue is gone.
However, the test of `TextureTransformTest.gltf` itself does not seem to pass.

[PlayCanvas v1.3.0 + TextureTransformTest.gltf result:](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformTest&scale=1.0&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/85918740-5d6e2880-b8a0-11ea-86e3-32df2df3da48.png)

Isn't the `KHR_texture_transform` extension still supported?

**Comment by slimbuck** [comment]
Hi @cx20,

We do support KHR_texture_transform, but only offset and scale (not rotation). The failed tests are using rotation and so we show an incorrect result. We'd need to modify the way our UVs are transformed in the engine to get this to work.

Thanks!

**Comment by cx20** [comment]
@slimbuck Thanks for the reply. I think this issue can be closed because I think it will be another issue (or feature request) when it comes to enhancing an extension.
If you have plans to enhance the extension, you can close it as it's implemented.

**Comment by willeastcott** [comment]
@cx20 I think it's OK to leave this open for now. When we implement UV rotation, we'll close this issue. Thanks for reporting!

**Comment by cx20** [comment]
I changed PlayCanvas from v1.31.0 to v1.32.0. Unfortunately, it is displayed more distorted than before.
[PlayCanvas v1.3.2 + TextureTransformTest.gltf result:](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformTest&scale=1.0&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/87859238-8f8a1c00-c96e-11ea-983b-dd9be037e3d7.png)

And I don't know if it's related, but the Texture Settings Test also seems to fail.
[PlayCanvas v1.3.2 + TextureSettingsTest.gltf result:](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=TextureSettingsTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/87859285-f3ace000-c96e-11ea-8ef7-a73a59c6cab9.png)
I think this test passed before. (It is not confirmed from what version the display content was broken.)

**Comment by slimbuck** [comment]
Thanks again @cx20! We actually fixed the normal tangent test in the latest release and I forgot to adjust the texture transform. Will fix this ASAP!

**Comment by slimbuck** [comment]
Only part of this is fixed (texture transform test now works as well as possible). I will address texture settings test next.

**Comment by cx20** [comment]
@slimbuck Thanks. I have confirmed in the latest version has been partially fixed.
[PlayCanvas v1.33.0-dev + TextureTransformTest.gltf result:](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformTest&scale=1.0&type=glTF)

**Comment by willeastcott** [comment]
Thanks @cx20 - can you verify this is fixed too:

https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF

If so, can you change the cross to a tick please? 😄

**Comment by cx20** [comment]
@willeastcott Thank you for telling me. I also confirmed the fix for `NormalTangentTest.gltf`. Currently the [gltf-test](https://github.com/cx20/gltf-test#feature-test-models) status is green.
