### ISSUE TITLE
Particle rendering Issue with Samsung Exynos CPU on Android 12

### ISSUE THREAD

**Issue by CMRDX** [playcanvas/engine#3967]
After recieveing bugreports we've discovered that some of our games are not rendering at all on Samsung devices that are using a variant of the Exynos CPU. 
We specifically tested on the Samsung Galaxy S10e and S10+ running Android 12. The problem could not be reproduced on the S10+ with Android 11. 
This issue might be related to: 
* https://github.com/playcanvas/engine/issues/3460

It can be reproduced when opening the sample project I referenced in the linked issue. When we ran the games with WebGL 1 we did not encounter the bug. Remote debugging on the S10e leat to the following error log: 
[playcanvas.redox-interactive.com-1643626936209_PARTICLES.log](https://github.com/playcanvas/engine/files/7971706/playcanvas.redox-interactive.com-1643626936209_PARTICLES.log)

Ps.: [Forum Post](https://forum.playcanvas.com/t/rendering-issue-with-samsung-exynos-cpu-on-android-12/24116)

**Comment by CMRDX** [comment]
@yaustar  it affects the whole game this time, not just the particle effects.

**Comment by mvaligursky** [comment]
Is there some repro project (ideally a simple one) we could reproduce this?

**Comment by CMRDX** [comment]
https://playcanvas.com/editor/project/828090 
This is the project we used to test the particle behaviour in the previously mentioned issue. It can be used to reproduce this problem as well.

**Comment by yaustar** [comment]
While the particles are rendering incorrectly, the scene is still rendering for me. Is there a way we can repro the issue where the game is not rendering at all?

**Comment by yaustar** [comment]
With the scene you linked above, we don't get the shader warnings/errors on device:

![image](https://user-images.githubusercontent.com/16639049/151954238-0124d006-dc46-4f2b-98b7-cbe4dca58027.png)

**Comment by yaustar** [comment]
We are requesting a device with this spec that we can access via our device lab

**Comment by CMRDX** [comment]
As a reference, these are the results we got on the sample project. (Samsung Galaxy S10+ Android 12)

![Screenshot_20220201-114944_Chrome](https://user-images.githubusercontent.com/75259672/151956055-6465fac2-f569-4b8b-90d1-3d845dff49c7.jpg)
![Screenshot_20220201-114901_Chrome](https://user-images.githubusercontent.com/75259672/151956061-90675518-7830-4b3d-80b8-36c4232b4090.jpg)

**Comment by yaustar** [comment]
There are two images, what's the difference between the two?

**Comment by CMRDX** [comment]
> There are two images, what's the difference between the two?

updated my previous comment

**Comment by yaustar** [comment]
Got a second confirmation from Leonidas on Discord that it crashes/doesn't render on their Exynos 9820 tablet on Android 12 too.

Engine 1.50.2 doesn't crash on their tablet

**Comment by yaustar** [comment]
We are ordering a S10E device to investigate

**Comment by mvaligursky** [comment]
this could be related, another webgl engine has similar issue:
https://www.html5gamedevs.com/topic/47939-webgl-flickering-on-samsung-s21-android-12/

We use DYNAMIC_DRAW for particle rendering.

**Comment by mvaligursky** [comment]
I've created a support request on Samsung Internet forum, as I have not found better place to do this yet.
https://forum.developer.samsung.com/t/browser-does-not-run-some-webgl2-content-on-android-12-devices/18866

**Comment by mvaligursky** [comment]
I have the device now and can reproduce it. I've tested all Graphics examples here: https://playcanvas.github.io/ and all work without crashes (particle based one look incorrect, which is a separate issue, but possibly related), apart from this one, which reproduces the crash: https://playcanvas.github.io/#/graphics/portal 

Two interesting notes from my testing:

1. After few of the shader compiles fail, we get this in the console:
```
launch:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
playcanvas.dbg.js?version=1.51.7:4672 pc.GraphicsDevice: WebGL context lost.
```
which suggests the device / driver has crashed, we lost the device. The device does not get restored anymore (which is should), which is the actual reason the app does not run.

2. When disabling some entities in the repro scene, I can get some simple shaders to fail compilation too. It's likely that internally the Particle shader fails first, and then all following shaders, including simple ones like this:

```
launch.js:15178 Failed to compile vertex shader:


1:	#version 300 es
2:	#define attribute in
3:	#define varying out
4:	#define texture2D texture
5:	#define GL2
6:	#define VERTEXSHADER
7:	attribute vec2 vertex_position;
8:	
9:	varying vec2 vUv0;
10:	
11:	void main(void)
12:	{
13:		gl_Position = vec4(vertex_position, 0.5, 1.0);
14:		vUv0 = vertex_position.xy*0.5+0.5;
15:	}
16:	
```

It seems that when we compile ParticleSystem shader, the driver gets into some incorrect state, and then fails to compile / do other things.

**Comment by mvaligursky** [comment]
for the record, this is the renderer I'm testing on:
unmaskedRenderer: **Mali-G76**
we could skip GPU particles on those, but that is more widely used GPU than on Samsung.

**Comment by mvaligursky** [comment]
it somehow seems to be related to this render target
https://github.com/playcanvas/engine/blob/382f8330089efe5796c3dd5eda680651378cf5c4/src/scene/particle-system/particle-emitter.js#L669-L672

which is then used here
https://github.com/playcanvas/engine/blob/382f8330089efe5796c3dd5eda680651378cf5c4/src/scene/particle-system/gpu-updater.js#L171-L176

But I'm not sure what the problem is, I cannot replicate it using render-to-texture example with the same render target, nor can fix this with changes to texture format / filtering.

**Comment by mvaligursky** [comment]
also, forcing cpu update fixes it
`this.useCpu = true;` (inside emitter code)

**Comment by CMRDX** [comment]
We tried setting the particles to a different sort mode than [PARTICLESORT_NONE](https://github.com/playcanvas/engine/blob/15b8bebc5348c15b3ef199d92da07d9f1517e904/src/scene/particle-system/particle-emitter.js#L254) which should also [set this.useCpu to true](https://github.com/playcanvas/engine/blob/15b8bebc5348c15b3ef199d92da07d9f1517e904/src/scene/particle-system/particle-emitter.js#L584) and can confirm that this fixes the problem.

**Comment by slimbuck** [comment]
nice detective work @mvaligursky !!

**Comment by Technostalgic** [comment]
Has this been officially resolved? Or should I just be using PARTICLESORT_NONE for the time being? 
I don't have a device to test it on so I can't try it myself 😔

**Comment by mvaligursky** [comment]
but see the update on Samsung's forum:
`Did you check on any recent devices, like S20/21 or note 20? The problem was solved on my note 20 ultra 5G.`

Does anybody have one of these devices to test on (must have `Exynos CPU`) ? 
I only have `S10E`

**Comment by Technostalgic** [comment]
I had a co worker with an S10E also test it out, issue still seems to be persisting

**Comment by CMRDX** [comment]
> Has this been officially resolved? Or should I just be using PARTICLESORT_NONE for the time being? I don't have a device to test it on so I can't try it myself 😔

To clarify: you should NOT use PARTICLESORT_NONE for the time being to avoid the problem. :)

**Comment by yaustar** [comment]
As we think this is a hardware driver issue, we've created a workaround that forces using the CPU on ARM based Samsung devices: https://github.com/playcanvas/engine/pull/4147

I expect this to go out with engine 1.53

**Comment by yaustar** [comment]
Should we close this? We haven't really fixed this, just worked around it 😅

**Comment by CMRDX** [comment]
You're right, reopened it 👍 Wanted to let you know that we tested the issue with the new engine version 1.53.0 and can confirm that it works with our test project on the affected devices. Looking forward to the official engine release.

**Comment by yaustar** [comment]
Awesome, thanks for the feedback @CMRDX !

**Comment by yaustar** [comment]
Closing this as this is no longer reproducible. See PR https://github.com/playcanvas/engine/pull/5255/
