### ISSUE TITLE
v1.63.0 forces draco re-download when initializing workers

### ISSUE THREAD

**Issue by pavle-goloskokovic** [playcanvas/engine#5307]
`initializeWorkers` method in `draco-decoder.js` forces re-download and re-compile of draco library regardless of if it is already loaded or not:

https://github.com/playcanvas/engine/blob/2845fc6cd710f1460fb867702467c25dcae7456d/src/framework/parsers/draco-decoder.js#L186

which you can also see in requests list below:

![image](https://user-images.githubusercontent.com/7340300/236419720-a442abfd-db8c-4cbd-81c3-9bd37ed67742.png)

This also removes ability when using engine only to download draco module in parallel or before downloading the engine, in effect increasing total loading time.

Is it possible for this logic to skip draco downloading if it can detect that it is already loaded, or if defined in `config` similar to `lazyInit` option?

**Comment by slimbuck** [comment]
Hi @pavle-goloskokovic,

Thanks for bringing this to our attention, we definitely don't want to do double work.

The reason it's downloading twice is that `draco.wasm.wasm` asset has `preload` enabled. So the asset is being preloaded by the module system and then draco webworkers are also loading the modules.

We will update the store item to disable preload when 1.63 is released. Till then you can get this working in your project by disabling preload on `draco.wasm.wasm`.

Thanks!

**Comment by pavle-goloskokovic** [comment]
Thanks for the response!

I would rather prefer if it would be the other way around - preload draco asset and then have webworkers detect if it was preloaded, downloading it only in case if it was not.

The way this is coded now still prevents loading draco before or in parallel with the engine, which was not an issue with previous versions and seems like a breaking change. Any thoughts on this?

Is it possible for this logic to skip draco downloading if it can detect that it is already loaded, or if defined in config similar to `lazyInit` option?

**Comment by slimbuck** [comment]
Yeah you're right preloading modules is important. Lemme see what I can figure out.

**Comment by pavle-goloskokovic** [comment]
Thanks for addressing this promptly @slimbuck!

I'll test next release when it's out.

**Comment by slimbuck** [comment]
Fix has been released.

**Comment by pavle-goloskokovic** [comment]
@slimbuck the issue was not fixed.

The way this is coded requires for draco to be downloaded using `pc.dracoInitialize()` call, effectively preventing draco module from being loaded before or in parallel with the engine.

Possible solution would be instead of forcing downloading here:
https://github.com/playcanvas/engine/blob/2845fc6cd710f1460fb867702467c25dcae7456d/src/framework/parsers/draco-decoder.js#L186

to be able to detect if the module was already loaded, and pass it to workers instead, and only if there is no module already loaded to download it.

This was not an issue in versions prior to `1.63.*`, before draco decoding refactor, and is a breaking change compared to previous versions.

**Comment by slimbuck** [comment]
I'd love to know if there is a better way of handling this though, so let me know if you have any ideas! :)
